spring:
  cloud:
    nacos:
      # Spring Cloud Nacos Discovery 配置项
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
#        namespace: dev # Nacos 命名空间
    sentinel:
      transport:
        port: 10003
        dashboard: localhost:8080
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    lettuce:
      pool:
        max-idle: 200
        min-idle: 10