server:
  port: 10003

spring:
  # Application 的配置项
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: management-web
          uri: lb://management-web
          predicates:
            - Path=/management-web/**
          filters:
            - StripPrefix=1
        - id: security-server
          uri: lb://security-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: plat-product
          uri: lb://plat-product
          predicates:
            - Path=/plat-product/**
          filters:
            - StripPrefix=1
  # Profile 的配置项
  profiles:
    active: local
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
#      - "/management-web/**"
#      - "/auth/crateToken"
logging:
  level:
    org.springframework:cloud.gateway: debug