spring:
  # 数据源配置项
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_admin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #    Spring Cloud 配置项
  cloud:
    nacos:
      # Spring Cloud Nacos Discovery 配置项
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
#        namespace: dev # Nacos 命名空间
  flyway:
    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
    enabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 验证错误时 是否自动清除数据库 高危操作!
    clean-on-validation-error: false
    locations: classpath:/db/ #可以配置多个值
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    lettuce:
      pool:
        max-idle: 200
        min-idle: 10
