server:
  port: 10005
spring:
  # Application 的配置项
  application:
    name: trade-service
  # Profile 的配置项
  profiles:
    active: local
  # SpringMVC 配置项
#  mvc:
#    throw-exception-if-no-handler-found: true # 匹配不到路径时，抛出 NoHandlerFoundException 异常
#    static-path-pattern: /doc.html # 静态资源的路径

# MyBatis Plus 配置项
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出详细sql
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.boot.st.tradeserver.dataobject

# Swagger 配置项
swagger:
  title: 交一服务
  description: 交一
  version: 1.0.0
  base-package: cn.boot.st.tradeserver.controller

#启用 httpclient
feign:
  # Feign 客户端配置，对应 FeignClientProperties 配置属性类
  client:
    # config 配置项是 Map 类型。key 为 Feign 客户端的名字，value 为 FeignClientConfiguration 对象
    config:
      # 全局级别配置
      default:
        logger-level: BASIC
      # 客户端级别配置
      demo-provider:
        logger-level: FULL
  httpclient:
    enabled: true
#  sentinel:
#    enabled: true

# 自定义redis key
redis:
  database: plat
  backend-web:
    token: 'ums:token'
    access-token-expire-time-millis: 21600
    refresh-token-expire-time-millis: 43200 #

# Actuator 监控配置项
management:
  server.port: 38087 # 独立端口，避免被暴露出去
  endpoints.web.exposure.include: '*' # 暴露所有监控端点